[package]
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
name = "icalendar"
version = "0.1.0"
license = "MIT/Apache-2.0"

description = "Early, minimal icalendar crate."
keywords = ["calendar", "ical", "ics"]

documentation = "https://docs.rs/icalendar/"
repository = "https://github.com/hoodie/icalendar-rs"
readme = "README.md"

include = [
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
]


[dependencies]
chrono = "0.2"
#error-chain = "*"
#vobject = {path="../hub/vobject"}

[dependencies.uuid]
features = ["v4"]
version = "0.3"
